# Creating a model which predicts the future number using LSTM & CNN LSTM

In [1]:
#importing required libraries
#will create a model which predicts a number from a univariate data
import numpy as np
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense

Using TensorFlow backend.


Here we need a sequence of data divided into input and output patterns and we need a time steps which are used as input and one time step is used as output for one_step_prediction
so this can be achived by deriving as funtion which is helps us to split the input data into 4 steps and output data into into one time step so here we create a funtion for achiving this

In [2]:
def split(sequence,n_steps):
    x,y = list(),list()
    for i in range(len(sequence)):
        end_x = i + n_steps #to find the end of the pattern
        if end_x > len(sequence)-1: #chk if we go beyond the sequence
            break
        seq_x,seq_y = sequence[i:end_x],sequence[end_x] #getting the input and output of the data
        x.append(seq_x)
        y.append(seq_y)
    return np.array(x),np.array(y)

In [3]:
#lets chk the working of above funtion 
import pandas as pd
data = [10,20,30,40,50,60,70,80,90]
n_steps = 3
a,b = split(data,n_steps)
for i in range (len(a)):
    print(a[i],b[i])

[10 20 30] 40
[20 30 40] 50
[30 40 50] 60
[40 50 60] 70
[50 60 70] 80
[60 70 80] 90


In [8]:
#here we pass the univariate data into a variable called data
data = [10,20,30,40,50,60,70,80,90]
#as discused we also create n_steps of split for spliting the data
n_steps = 4
x,y = split(data,n_steps)
#here we reshape the data for the model useage according to its artributes
n_feature = 1
x = x.reshape((x.shape[0],x.shape[1],n_feature))
#model creation
model = Sequential()
#cearting an hidden layer with 50 LSTM units and one single output
model.add(LSTM(50,activation='relu',input_shape=(n_steps,n_feature)))
model.add(Dense(1))
#compiling the model
model.compile(optimizer='adam',loss='mse')
#fitting the created model to the data
model.fit(x,y,epochs=300,verbose=0)
#by here we are done with creating the model
#so now lets chk and make prediction
x_input = np.array([12,22,33,44])
x_input = x_input.reshape((1,n_steps,n_feature))
y_pred = model.predict(x_input,verbose=0)
print("The approximate predicted value is: ",y_pred)

The approximate predicted value is:  [[54.541683]]


# implementing the same with CNN

In [5]:
#importing required libararies
from keras.layers import Flatten
from keras.layers import TimeDistributed
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D

In [7]:
#all the steps are performed in the same manner
df = [10,20,30,40,50,60,70,80,90]
s_steps = 4
#split into samples
x,y = split(df,s_steps)
#reshape
n_features = 1
n_seq = 2
n_steps = 2
x = x.reshape((x.shape[0],n_seq,n_steps,n_features))
#creating model
model = Sequential()
model.add(TimeDistributed(Conv1D(filters=64,kernel_size=1,activation = 'relu'),input_shape=(None,n_steps,n_features)))
model.add(TimeDistributed(MaxPooling1D(pool_size=2)))
model.add(TimeDistributed(Flatten()))
model.add(LSTM(50,activation='relu'))
model.add(Dense(1))
#compiling the model with adam optimizer
model.compile(optimizer='adam',loss='mse')
#fittng the model
model.fit(x,y,epochs=350,verbose=0)
#make prediction
x_input = np.array([60,70,80,90])
x_input = x_input.reshape((1,n_seq,n_steps,n_features))
y_predict = model.predict(x_input,verbose=0)
print("The approximate value is: ",y_predict)

The approximate value is:  [[102.76222]]
